### ISSUE TITLE
Torch Geometric Google Colab

### ISSUE THREAD

**Issue by nkasmanoff** [phlippe/uvadlc_notebooks#10]
**Tutorial**: -7

**Describe the bug**

The current torch version on Google Colab is 1.9.x. This is currently incompatible with the previously installed + imported PyTorch Geometric packages. 

**To Reproduce (if any steps necessary)**

Running the notebook as is. 

**Expected behavior**

PyTorch Geometric and it's companion packages should be installed. 

**Screenshots**
N/A

**Runtime environment (please complete the following information):**

This applies for Google Colab, but is applicable anytime torch 1.9 is used instead of a prior one. 

**Additional context**

Updating the cell as follows: 

`# torch geometric
try: 
    import torch_geometric
except ModuleNotFoundError:
    # You might need to install those packages with specific CUDA+PyTorch version. 
    # The following ones below have been picked for Colab (Jun 2021).
    # See https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html for details 
    !pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.9.0+cu101.html
    !pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.9.0+cu101.html
    !pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.9.0+cu101.html
    !pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.9.0+cu101.html
    !pip install torch-geometric
    import torch_geometric
import torch_geometric.nn as geom_nn
import torch_geometric.data as geom_data`

fixes the issue for me.

**Comment by phlippe** [comment]
Hi, thanks a lot for raising the issue! In the latest commit, I made the installation dependent on the used CUDA and PyTorch version, so that this hopefully does not happen in the future. It works for me on Google Colab now. Feel free to reopen this issue if you still experience issues.
