### ISSUE TITLE
Not really a bug: images don't show well with dark background

### ISSUE THREAD

**Issue by jerronl** [phlippe/uvadlc_notebooks#101]
**Tutorial**: -1 

**Describe the bug**
Many of the images are with transparent background and black text foreground. There fore they merged with dark background if the browser or IDE (in my case, I use VSCode to open the notebooks) are set with dark themes.

**To Reproduce (if any steps necessary)**
1. Set the browser with dark background. Or set the IDE with dark theme.
2. Go to any notebook
3. Check the images
4. The text, if they are black or dark gray, would merge with the dark background and hard to be viewed.

**Expected behavior**
We can set the background with white color and the images would be shown clearly regardless users' settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/28072469/236703293-48a7444b-bd09-4c7e-9403-6aad95766905.png)

**Runtime environment (please complete the following information):**
 - Local computer or Google Colab? Both
 - Run on CPU only or GPU? NA

**Additional context**

**Comment by phlippe** [comment]
@jerronl That's a very good point, I didn't think of that before. Let me check if I can add a default background color to all SVG images.

**Comment by phlippe** [comment]
Thanks again for pointing that out. Added background color to all images in a2fe2d3cad57fc56e6898d30c8bbd78b3e0a1c0e. Let me know in case you spot any that images that are still hard to read in dark mode :)
