### ISSUE TITLE
Example job script in Guide 1 is depricated on Snellius

### ISSUE THREAD

**Issue by danilodegoede** [phlippe/uvadlc_notebooks#104]
In [Guide 1: Working with the Lisa cluster](https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/tutorial1/Lisa_Cluster.html#:~:text=%23SBATCH%20%2D%2Dpartition%3Dgpu_shared_course-,%23SBATCH%20%2D%2Dgres%3Dgpu%3A1,-%23SBATCH%20%2D%2Djob%2Dname%3DExampleJob), the job script is depricated in how it asks for a GPU on Snellius.

The line `#SBATCH --gres=gpu:1` only works for interactive nodes on Snellius. In a normal job script, one should instead use `#SBATCH --gpus=1`. Otherwise, CUDA will throw a RuntimeError saying that no GPUs are available. 

I know that the guide is originally intended for the Lisa cluster, but it might be something to keep in mind in case you are planning to update it to Snellius at some point.

**Comment by phlippe** [comment]
Hey Danilo, thanks for pointing this out! For now, I have added a note on it in the Lisa guide (4d980d9ae412c62e3a8b6ba600fd83d283cf8afc). I don't know what we will use for the DL1 course next year (e.g. if there will be a Lisa 2.0 cluster or only Snellius), so I'll try to update the guide fully once that is decided.
