### ISSUE TITLE
Tutorial 2 : 

### ISSUE THREAD

**Issue by awe-sim** [phlippe/uvadlc_notebooks#11]
**Tutorial**: 2 (Introduction to PyTorch)

**Describe the bug**
The overlay rendered in cell [59] is incorrect. It works for the given XOR dataset. But if you change the dataset to OR or AND (which are not rotationally symmetric), it doesn't work anymore.

**To Reproduce (if any steps necessary)**
1. Go to cell [41].
2. Replace `label = (data.sum(dim=1) == 1).to(torch.long)` with `label = (data.sum(dim=1) != 0).to(torch.long)` (OR) or `label = (data.sum(dim=1) == 2).to(torch.long)` (AND).
3. Execute all cells between [41] and [59]
4. You'll find that the overlay generated in cell [59] does not reflect the active dataset correctly, even though accuracy is 100%.

**Expected behavior**

**Screenshots**

**Runtime environment (please complete the following information):**
 - Local computer or Google Colab?
 - Run on CPU only or GPU?

**Additional context**

**Comment by phlippe** [comment]
Thanks for pointing it out and the pull request!
