### ISSUE TITLE
Can PositionalEncoding used with position information?

### ISSUE THREAD

**Issue by jerronl** [phlippe/uvadlc_notebooks#114]
It seems to me that PositionalEncoding would always be encoded with the relative position in the sample. Can we also use it with some known position information? For example, one of the input feature could be a time stamp, can we use the value of it to decide what would be the offset of in pe would be used?

current code:
```

    def forward(self, x):
        x = x + self.pe[:, :x.size(1)]
        return x
```

possible new pseudo code

```

    def forward(self, x):
        y=x[:,date_col,]
        x = x + self.pe[:, y :y+x.size(1)]
        return x
```

**Comment by phlippe** [comment]
Sure! You can input any extra features to the transformer.
