### ISSUE TITLE
Introduction_to_PyTorch.ipynb: Mean Sigma Formula 

### ISSUE THREAD

**Issue by kmouts** [phlippe/uvadlc_notebooks#117]
The mean value formula uses the "|𝑥|" notation to denote the number of the _xi_ elements in the 𝑥 vector:

𝑦=1/|𝑥| * ∑𝑖[(𝑥𝑖+2)2+3]

However |𝑥| usually means the [magnitude](https://www.cuemath.com/magnitude-of-a-vector-formula/) of the vector.

**Comment by phlippe** [comment]
Good point, that may be a bit confusing here. Made it more explicit in 662890a.
