### ISSUE TITLE
"Getting runtime error"

### ISSUE THREAD

**Issue by rakibMahmud** [phlippe/uvadlc_notebooks#121]
"Tutorial 16: Meta-Learning - Learning to Learn" I am following this tutorial...but while running the code i got this error "RuntimeError: setStorage: sizes [], strides [], storage offset 15, and itemsize 8 requiring a storage size of 128 are out of bounds for storage of size 0". Can you help me with this.

**Comment by phlippe** [comment]
Hi, I just reran Tutorial 16 on Google Colab, and it finished without errors. Can you give a closer description of how you got the error?

**Comment by rakibMahmud** [comment]
Thank you. the error has been solved. Can you please tell me how you use the tensorboard here...I have already installed the tensorboard and saved the same model you used to test on my dataset. But i was unable to use the tensorboard.
