### ISSUE TITLE
Copyright on a gif

### ISSUE THREAD

**Issue by mariakesa** [phlippe/uvadlc_notebooks#133]
Hello:-)

My name is Maria. I'm writing a web-based self-study thesis on using Visual Transformers CLS representations to predict neural activity in mouse cortex. I was wondering, can I use your ViT GIF here https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/tutorial15/Vision_Transformer.html in my webpage if I cite you next to the GIF? 

Thank you so much for an awesome course, it's great!

All the very best,
Maria

**Comment by mariakesa** [comment]
Thanks! I will contact the professors! I didn't notice the email on the site before [y.m.asano@uva.nl](mailto:y.m.asano@uva.nl) Do you think that's the correct person to ask?

I found the course through Googling, I think I searched for deep learning or transformers courses something or other, it came up pretty high in the hit list:-)

Anyway, thanks a bunch-- happy 2024!

**Comment by phlippe** [comment]
Hi Maria,

Thanks for reaching out! I took the GIF from here with giving credit to them: https://github.com/lucidrains/vit-pytorch/blob/main/images/vit.gif. I recommend doing the same and citing Phil Wang instead of us :)

Best,
Phillip

**Comment by mariakesa** [comment]
Great, that's awesome-- thanks so much:-) Sorry, I didn't notice the citation!
