### ISSUE TITLE
[Question]Tutorial 7 GNN

### ISSUE THREAD

**Issue by sy-eng** [phlippe/uvadlc_notebooks#138]
Thank you for your great tutorials!

I have 2 questions about tutorial 7 GNN, especially for JAX.

1, [Confirmation] In Graph Convolutions section, it is mentioned that H^(l+1) is σ(hat{D}^{-1/2}hat{A}hat{D}^{-1/2}HW) and we can simply divide the summed messages by the number of neighbors instead of defining a matrix hat{D}.
The implementation does not look like the implementation of H^(l+1) = σ(hat{D}^{-1/2}hat{A}hat{D}^{-1/2}HW), but that of H^(l+1) = σ(hat{D}^{-1}hat{A}HW).
Is it true?

H^(l+1) = σ(hat{D}^{-1}hat{A}HW) is mentioned in a blog post (https://tkipf.github.io/graph-convolutional-networks/).
And it can have similar effect to H^(l+1) is σ(hat{D}^{-1/2}hat{A}hat{D}^{-1/2}HW).

2, [Question] In __call__() function in cell 6 in JAX tutorial, the codes shown below look wrong.

> logit_parent = (node_feats * self.a[None,None,:,:self.a.shape[0]//2]).sum(axis=-1)
> logit_child = (node_feats * self.a[None,None,:,self.a.shape[0]//2:]).sum(axis=-1)

Aren't they :
> logit_parent = (node_feats * self.a[None,None,:,:self.a.shape[1]//2]).sum(axis=-1)
> logit_child = (node_feats * self.a[None,None,:,self.a.shape[1]//2:]).sum(axis=-1)

Now, this makes no error because the size of self.a is (2, 2). 

Thank you.

**Comment by phlippe** [comment]
Hi @sy-eng,
 
1. Yes that's correct, since D is a diagonal matrix in our case, you can rewrite the equation accordingly. The full equation form is a bit more general.
2. Good point, this is indeed a typo. Will be fixed in the next commit, thanks!
