### ISSUE TITLE
the code of expand_mask is not consistent with the comment

### ISSUE THREAD

**Issue by chenliang-xu** [phlippe/uvadlc_notebooks#143]
**Tutorial**: 6 (Fill-in number of tutorial)

https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/JAX/tutorial6/Transformers_and_MHAttention.html

**Describe the bug**

the code of expand_mask is not consistent with the comment. The comment suggests a rank bigger or equal to 2 is supported while the code does not support rank 2.

**Comment by phlippe** [comment]
Thanks, somehow forgot the equals in `>=`. Fixed in 20d8b6e87a4afecc66f8192a0f53d11de16e068f
