### ISSUE TITLE
Dataset unavailable

### ISSUE THREAD

**Issue by gerritgr** [phlippe/uvadlc_notebooks#38]
Hi,

the dataset (https://surfdrive.surf.nl/files/index.php/s/6YWMO1eiVXI4EkB/download) that is used in https://github.com/phlippe/uvadlc_notebooks/blob/master/docs/tutorial_notebooks/DL2/sampling/graphs.ipynb seems to be unavailable. 
Is there any way to still download (or generate) it?

Best and thanks for your help,
Gerrit

**Comment by phlippe** [comment]
Hi Gerrit, thanks for pointing this out. I'll contact the author of that notebook and check whether we can re-enable the download link of the dataset, or find an alternative way for accessing the dataset.

**Comment by phlippe** [comment]
A new functional download link has been added with #39

**Comment by gerritgr** [comment]
Thanks!
