### ISSUE TITLE
Tutorial 11 : Runtime error in train_flow function

### ISSUE THREAD

**Issue by sy-eng** [phlippe/uvadlc_notebooks#54]
Thank you for your great tutorials!

I tried tutorial 11 on my laptop (it has no gpu.) 
and I got a runtime error in train_flow function.
Its error message said map_location in torch.load should be set.
So I modified 
ckpt = torch.load(pretrained_filename)
to
ckpt = torch.load(pretrained_filename, map_location=device).

I guess this modification is good for PCs without gpu.

Thank you.

**Comment by phlippe** [comment]
Hi @sy-eng, thanks for pointing this out and already preparing the solution! The new commit should now support loading the NFs on CPU. Thanks!

**Comment by sy-eng** [comment]
Thank you!
