### ISSUE TITLE
 __init__() got an unexpected keyword argument 'progress_bar_refresh_rate'

### ISSUE THREAD

**Issue by Prayag22** [phlippe/uvadlc_notebooks#59]
Could you please help with this line of code. I tried pip install progress_bar but it did not work.
results = {}
for num_imgs_per_label in [10, 20, 50, 100, 200, 500]:
    sub_train_set = get_smaller_dataset(train_feats_simclr, num_imgs_per_label)
    _, small_set_results = train_logreg(batch_size=64,
                                        train_feats_data=sub_train_set,
                                        test_feats_data=test_feats_simclr,
                                        model_suffix=num_imgs_per_label,
                                        feature_dim=train_feats_simclr.tensors[0].shape[1],
                                        num_classes=10,
                                        lr=1e-3,
                                        weight_decay=1e-3)
    results[num_imgs_per_label] = small_set_results
 Thanks and regards.

**Comment by phlippe** [comment]
Hi, thanks for pointing this out! This argument was removed in the latest version of PyTorch Lightning and replaced with `enable_progress_bar`. The newest commit 984369e581184b961550adf12eb6cff66e7a6043 should fix it now.
