### ISSUE TITLE
Supervised Contrastive Learning

### ISSUE THREAD

**Issue by deadsoul44** [phlippe/uvadlc_notebooks#61]
https://arxiv.org/pdf/2004.11362.pdf

It would be great to have this paper implemented in Jax.

Thanks for the great work.

**Comment by phlippe** [comment]
Hi, thanks for the suggestion! It would indeed a natural step as a follow-up notebook to SSL.

**Comment by Purna-hub** [comment]
dear sir, Thank you very much for your informative repo. Please guide me how to implement GNN for text classification on custom dataset
