### ISSUE TITLE
Question regarding image transforms in SimCLR Tutorial

### ISSUE THREAD

**Issue by BalajiAI** [phlippe/uvadlc_notebooks#63]
In Tutorial 17, SimCLR implementation; you've mentioned that you didn't use color distortion incase of train image transforms. Because it changes the color distribution which is an important feature for classification.
But you've used RandomGrayscale(p=0.2) in the train image transforms. Converting an RGB image to Grayscale image changes the color distribution right?

Also can you point to the resource which tells that color distribution is an important feature?

**Comment by phlippe** [comment]
Hi, you are right that a Grayscale transformation does change the color distribution. However, it does so in a very different manner than color distribution and gives a unique pattern. In other words, if the model sees a colorful image, it knows that these colors are the correct ones. If I use color distortion, I would remove this ability from the model, and hence it cannot use the color anymore as possible feature. If I use grayscaling, the model simply recognizes when the color has been removed and will try to classify the image as good as possible without colors. Nonetheless, it will learn to use colors as an important feature.

Color being an important feature in many classification task can be intuitively seen when you perform a histogram analysis on e.g. CIFAR10. Images of ships and airplanes will in general have a very high proportion of blue pixels, while horses often have green as a background.

**Comment by BalajiAI** [comment]
Thanks, @phlippe. I understood now.
