### ISSUE TITLE
Possible typo in Tutorial 6

### ISSUE THREAD

**Issue by insdout** [phlippe/uvadlc_notebooks#65]
**Tutorial**: 6 

**Describe the bug**
It seems that there is a typo in Milti-Head markdown cell:

We refer to this as Multi-Head Attention layer with the learnable parameters $W_{1...h}^{Q}\in\mathbb{R}^{D\times d_k}$, $W_{1...h}^{K}\in\mathbb{R}^{D\times d_k}$, $W_{1...h}^{V}\in\mathbb{R}^{D\times d_v}$, and $W^{O}\in\mathbb{R}^{h\cdot d_k\times d_{out}}$ ($D$ being the input dimensionality). Expressed in a computational graph, we can visualize it as below (figure credit - [Vaswani et al., 2017](https://arxiv.org/abs/1706.03762)).

Here instead of $W^{O}\in\mathbb{R}^{h\cdot d_k\times d_{out}}$,  it probably should say $W^{O}\in\mathbb{R}^{h\cdot d_v\times d_{out}}$

As the output is stacked V vectors of d_v dimensions.

**Screenshots**
The screenshot from original paper:
![Screenshot from 2022-12-25 01-31-38](https://user-images.githubusercontent.com/49560124/209449027-ab6ad7aa-b27f-458d-9f93-cb9481426d7a.png)

**Comment by phlippe** [comment]
Hi, thanks for pointing this typo out! This should be fixed with the newest commit ffea03ed82022579ed66e18e6748160d12ad1115.
