### ISSUE TITLE
Regarding QKV in vision transformer

### ISSUE THREAD

**Issue by FarahSaeed** [phlippe/uvadlc_notebooks#68]
**Tutorial**: -15 

Hi 

In this tutorial [tutorial 15 for vision transformer in pytorch](https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/tutorial15/Vision_Transformer.html)

I observed query, key and value being same in the attention block. 
`x = x + self.attn(inp_x, inp_x, inp_x)[0]`

In [tutorial 6](https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/tutorial6/Transformers_and_MHAttention.html) ,  the query, key and value are recieved from a projection.
`qkv = self.qkv_proj(x)`

In another vision transformer implementation [https://towardsdatascience.com/implementing-visualttransformer-in-pytorch-184f9f16f632](this) the queries, values and keys are received from a projection. 

I tried to find the source code of pytorch function multiheadattention. It seems like projection for query value and key is  not applied in definition as input tensor is same for query, key and value.

I wanted to know if I should manually project the input embedding to query, key and value them before forward passing to attention.

Thanks

**Comment by phlippe** [comment]
Hi, the MultiHead Attention layer in PyTorch integrates this projection directly in the same layer. You can find the code here: https://pytorch.org/docs/stable/_modules/torch/nn/modules/activation.html#MultiheadAttention
If the input tensor is of the same size for query, value and keys, this layer defines one weight to project the input to query, key and value:
`self.in_proj_weight = Parameter(torch.empty((3 * embed_dim, embed_dim), **factory_kwargs))`
This is the same strategy as used in Tutorial 6 and is usually more efficient for common embed_dim values. Therefore, you don't need to manually project the input in this layer.

**Comment by FarahSaeed** [comment]
Sounds good, thank you.
