### ISSUE TITLE
Tutorial 10: Tabulate Syntax error

### ISSUE THREAD

**Issue by ckim0922** [phlippe/uvadlc_notebooks#69]
**Tutorial 10**: -1 (Fill-in number of tutorial)

**Describe the bug**
I am expecting to receive a tabulate format of result but getting syntax error

**To Reproduce (if any steps necessary)**
Simply running the Google Colab notebook as attached.

**Expected behavior**
Suppose to produce a table of results

**Screenshots**
![image](https://user-images.githubusercontent.com/80383901/213919442-d392bbdb-6c88-41d0-98e1-3883bf44b2a3.png)

**Runtime environment (please complete the following information):**
 - Colab
 - CPU only

**Additional context**
I tried debugging by changing ["results"] to [result] but that didn't seem to work.

Could you please advise if you have any solution to the above problem?

**Comment by phlippe** [comment]
Hi, thanks for pointing this out! The `"results"` key should be written `'results'` instead, due to the f-string. The commit 7f907c6264908959dd1b4f61abba4c77438c232a should fix the bug.
