### ISSUE TITLE
the content is perfect (a word is misspelled)

### ISSUE THREAD

**Issue by yinpub** [phlippe/uvadlc_notebooks#70]
Thank all the authors. You did a good job and I like your job very much.
In week 8 energy model chapter, there is a sentence that
_The fundamental idea of energy-based models is that you can turn any function that predicts values larger than zero into a probability distribution by dviding by its volume_ 
I think that, _dviding_  means dividing.

**Comment by phlippe** [comment]
Hi, thanks for pointing this out! Commit 5f8a7c9fe003d2d19220c244fb6a640f8a4d22e4 should fix this typo now.
