### ISSUE TITLE
Incorrect normalization factor in attention

### ISSUE THREAD

**Issue by lebigot** [phlippe/uvadlc_notebooks#72]
**Tutorial**: 6

**Describe the bug**

The normalization in `scaled_dot_product()` doesn't use the correct dimension and is thus in general wrong.

**To Reproduce (if any steps necessary)**

This can be seen by printing `d_k`.

**Expected behavior**

The normalization quantity `d_k` should in fact be the "hidden" dimension of the queries or keys.

Thus, instead of
```python
def scaled_dot_product(q, k, v, mask=None):
    d_k = q.size()[-1]
```
we should have
```python
```python
def scaled_dot_product(q, k, v, mask=None):
    d_k = q.size()[-1]
```

**Comment by phlippe** [comment]
Hi, the normalization ensures that the variance of the dot product between one query and one key does not blow up and stay in the expected range of 1. The number of elements in the sum depend on the number of hidden dimensions/dimensionality size of the keys and queries, i.e. `d_k`. This is independent of the sequence length/number of keys/values and size of the value vectors. Hence, it can be determined by `q.size()[-1]` or `k.size()[-1]`, but can't be inferred by the values. Does this answer your question, or can you specify the bug more, e.g. by giving an example?

**Comment by lebigot** [comment]
You are correct. I just realized this 20 minutes after your response. Sorry for the false alert!
