### ISSUE TITLE
Not able to load pretrained models

### ISSUE THREAD

**Issue by ghoshsdeeep** [phlippe/uvadlc_notebooks#73]
I am not able to load the pretrained model
![enquiry](https://user-images.githubusercontent.com/12712069/223004413-9f84980b-99b2-4b9e-b6ca-3d44f46b6048.JPG)

Can you please help me to load the model?

**Comment by phlippe** [comment]
Hi, can you specify which tutorial you are trying to run?

**Comment by ghoshsdeeep** [comment]
Vision Transformers
Trying to load ViT.ckpt

**Comment by ghoshsdeeep** [comment]
I downloaded it from this path 

![Screenshot (79)](https://user-images.githubusercontent.com/12712069/223224206-6311a747-d9ce-4830-9fe6-aafc5a946e8d.png)
Just changed one line
![Screenshot (78)](https://user-images.githubusercontent.com/12712069/223224213-a32f280d-ecd7-4990-ab15-014ae1fcb57d.png)

**Comment by phlippe** [comment]
The error message suggests that the layer `input_layer` module was removed in the Vision Transformer. Can you verify that it is still there in your code?
