### ISSUE TITLE
[Question] Tutorial 9: no activation function after the encoder FC layer 

### ISSUE THREAD

**Issue by rigvova** [phlippe/uvadlc_notebooks#77]
Hello, 

I have a question regarding the activation functions in the Autoencoders guide.
In the *"[Tutorial 9: Deep Autoencoders](https://github.com/phlippe/uvadlc_notebooks/blob/master/docs/tutorial_notebooks/tutorial9/AE_CIFAR10.ipynb)"* notebook the Encoder layers are defined by the code:
```
self.net = nn.Sequential(
    nn.Conv2d(num_input_channels, c_hid, kernel_size=3, padding=1, stride=2), # 32x32 => 16x16
    act_fn(),
    ...
    nn.Conv2d(2*c_hid, 2*c_hid, kernel_size=3, padding=1, stride=2), # 8x8 => 4x4
    act_fn(),
    nn.Flatten(), # Image grid to single feature vector
    nn.Linear(2*16*c_hid, latent_dim)
)
```
while the Decoder consists of a Linear layer followed by deconvolutions:
```
self.linear = nn.Sequential(
    nn.Linear(latent_dim, 2*16*c_hid),
    act_fn()
)
self.net = nn.Sequential(
    ...
)
```

I see that there is no activation function after the Linear layer in the Encoder. I have tried adding `act_fn()` right after it and got significantly worse results within the same number of training steps. So, is it generally a bad idea to add a non-linear activation function between two Fully Connected layers in an Autoencoder?

**Comment by phlippe** [comment]
Hi, the output of the linear layers are here the lower-level representation, i.e. encoding, of the model. By applying a non-linearity, you considerably limit the encoding space. For instance, if you would apply a ReLU, you limit the encoding space to only positive numbers.
Further, the encoding is the bottleneck of the model, and it is not intended as a typical layer which allows the model non-linear mappings. Thus, in general, you don't apply any non-linearity in there.

**Comment by vladimir-rigvava** [comment]
Got it, makes sense. Thank you!
