### ISSUE TITLE
typo in jax tutorial 7

### ISSUE THREAD

**Issue by murphyk** [phlippe/uvadlc_notebooks#88]
In https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/JAX/tutorial7/GNN_overview.html#Graph-Convolutions
you refer to the pytorch model, but it's actually jax :)

**Comment by phlippe** [comment]
Oh, thanks, that went undetected! Fixed in f830c5d3e6514eda8426c23d19cc56e3ece8902e
