### ISSUE TITLE
style suggestion for jax tutorial 11 (flows)

### ISSUE THREAD

**Issue by murphyk** [phlippe/uvadlc_notebooks#90]
The code uses the variable `ldj` but this is never explained.
Just say that ldj = log-det-jacobian :)

**Comment by murphyk** [comment]
Also, in cell 16, you say `Test MultiheadAttention implementation` but this is using a gated ConvNet, not attention.

**Comment by phlippe** [comment]
Didn't notice that I hadn't explained the abbreviation at all, thanks! :)
Fixed in fa80c4da32b8a147996717fba08963dcc11be9f7
