### ISSUE TITLE
torch tutorial 8 (EBMs): small change needed at end to print scalar tensor using torch 2.0

### ISSUE THREAD

**Issue by murphyk** [phlippe/uvadlc_notebooks#97]
**Tutorial**: -1 (Fill-in number of tutorial)

https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/tutorial8/Deep_Energy_Models.html

**Describe the bug**

In the `compare_images` function, the line `print(f"Score original image: {score1:4.2f}")` raises the error
`unsupported format string passed to Tensor.__format__`. Need to change this to `score1[0]` and `score2[0]`.
Full code below

```
@torch.no_grad()
def compare_images(img1, img2):
    imgs = torch.stack([img1, img2], dim=0).to(model.device)
    score1, score2 = model.cnn(imgs).cpu().chunk(2, dim=0)
    grid = torchvision.utils.make_grid([img1.cpu(), img2.cpu()], nrow=2, normalize=True, range=(-1,1), pad_value=0.5, padding=2)
    grid = grid.permute(1, 2, 0)
    plt.figure(figsize=(4,4))
    plt.imshow(grid)
    plt.xticks([(img1.shape[2]+2)*(0.5+j) for j in range(2)],
               labels=["Original image", "Transformed image"])
    plt.yticks([])
    plt.show()
    print(f"Score original image: {score1[0]:4.2f}"). ####
    print(f"Score transformed image: {score2[0]:4.2f}").  ###
```

**Runtime environment (please complete the following information):**
 - Local computer or Google Colab?
 - Run on CPU only or GPU?

colab with GPU
torch 2.0

**Comment by phlippe** [comment]
Thanks! Fixed in 95212a10d9eb7b456a7e781313dd70de2cf4f5c6.
